### ISSUE TITLE
The "main" definition in "package.json" is broken

### ISSUE THREAD

**Issue by swernerx** [Haixing-Hu/vue-i18n#4]
The main block should contain a single module ID, not an array. Therefor it is not installable via jspm right now.

Current code:

```
  "main": [
    "src/vue-i18n.js"
  ],
```

Fixed code:

```
  "main": "src/vue-i18n.js",
```

Thanks for fixing!

**Comment by Haixing-Hu** [comment]
The pull request has been merged. Thank you.
